#!/usr/bin/env bash
#
# Deploy the split payment stack to GCP (Cloud Functions Gen2), in order.
#
# Prereqs: gcloud auth application-default login (or user creds), APIs enabled,
# Firestore in GCP_REGION, bucket BUCKET_NAME exists.
#
# Usage:
#   cp scripts/deploy.env.example deploy.env
#   # edit deploy.env — do not commit
#   ./scripts/deploy-gcp-payment-stack.sh
#
# Or pass env file:
#   DEPLOY_ENV_FILE=deploy.env ./scripts/deploy-gcp-payment-stack.sh
#
# Re-run safe: if a function name already exists in GCP, deploy is skipped unless
# DEPLOY_FORCE=1. URLs are written to deploy.state (gitignored) for your notes.
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEPLOY_STATE_FILE="${DEPLOY_STATE_FILE:-${REPO_ROOT}/deploy.state}"
SUBSCRIPTION_WAS_PRESENT=""

if [[ -n "${DEPLOY_ENV_FILE:-}" && -f "${DEPLOY_ENV_FILE}" ]]; then
  # shellcheck source=/dev/null
  set -a && source "${DEPLOY_ENV_FILE}" && set +a
elif [[ -f "${REPO_ROOT}/deploy.env" ]]; then
  # shellcheck source=/dev/null
  set -a && source "${REPO_ROOT}/deploy.env" && set +a
fi

PROJECT_ID="${GCP_PROJECT:-}"
REGION="${GCP_REGION:-europe-west1}"

need_var() {
  local n="$1"
  if [[ -z "${!n:-}" ]]; then
    echo "Missing required variable: $n (set in deploy.env — see scripts/deploy.env.example)" >&2
    exit 1
  fi
}

need_var GCP_PROJECT
need_var GCP_REGION
need_var STORE_ORIGIN
need_var PROCESSOR_INGEST_SECRET
need_var BUCKET_NAME
need_var COORDINATES_SECRET_ID
need_var STRIPE_SECRET

FN_PROCESSOR="${FN_PROCESSOR:-secnum-payment-processor}"
FN_CHAIN_SERVER="${FN_CHAIN_SERVER:-secnum-chain-server}"
FN_CHAIN_ACTIVATE="${FN_CHAIN_ACTIVATE:-secnum-chain-activate}"
FN_ORDER_RESULT="${FN_ORDER_RESULT:-secnum-order-result}"
FN_PAYMENT_WORKER="${FN_PAYMENT_WORKER:-secnum-payment-worker}"
FN_STRIPE_ADAPTER="${FN_STRIPE_ADAPTER:-secnum-stripe-adapter}"

PUBSUB_PUSH_SA="${PUBSUB_PUSH_SA:-sa-pubsub-push}"
PUBSUB_TOPIC="${PUBSUB_TOPIC:-secnum-payment-events}"
PUBSUB_SUBSCRIPTION="${PUBSUB_SUBSCRIPTION:-secnum-payment-events-push}"
NODE_RUNTIME="${NODE_RUNTIME:-nodejs22}"
PYTHON_RUNTIME="${PYTHON_RUNTIME:-python312}"

phase() { echo ""; echo "=== $* ==="; }

run_invoker_bind() {
  local service="$1"
  local member="$2"
  local extra=()
  if [[ "${DEPLOY_USE_CONDITION_NONE:-}" == "1" ]]; then
    extra=(--condition=None)
  fi
  if gcloud run services add-iam-policy-binding "${service}" \
    --project="${PROJECT_ID}" \
    --region="${REGION}" \
    --member="${member}" \
    --role="roles/run.invoker" \
    "${extra[@]}" 2>/dev/null; then
    echo "Invoker: ${member} -> ${service}"
  else
    echo "(Invoker bind skipped or already present: ${member} -> ${service})"
  fi
}

fn_uri() {
  gcloud functions describe "$1" --gen2 --project="${PROJECT_ID}" --region="${REGION}" \
    --format='value(serviceConfig.uri)'
}

runtime_sa_email() {
  gcloud functions describe "$1" --gen2 --project="${PROJECT_ID}" --region="${REGION}" \
    --format='value(serviceConfig.serviceAccountEmail)'
}

force_deploy() {
  [[ -n "${DEPLOY_FORCE:-}" ]]
}

fn_exists() {
  gcloud functions describe "$1" --gen2 --project="${PROJECT_ID}" --region="${REGION}" &>/dev/null
}

# Persists non-secret URLs only. Do not store keys or PROCESSOR_INGEST_SECRET here.
write_deploy_state() {
  umask 077
  local tmp="${DEPLOY_STATE_FILE}.tmp"
  cat >"${tmp}" <<STATE
# Generated by deploy-gcp-payment-stack.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ) — do not commit
GCP_PROJECT=${PROJECT_ID}
GCP_REGION=${REGION}
FN_PROCESSOR=${FN_PROCESSOR}
FN_CHAIN_SERVER=${FN_CHAIN_SERVER}
FN_CHAIN_ACTIVATE=${FN_CHAIN_ACTIVATE}
FN_ORDER_RESULT=${FN_ORDER_RESULT}
FN_PAYMENT_WORKER=${FN_PAYMENT_WORKER}
FN_STRIPE_ADAPTER=${FN_STRIPE_ADAPTER}
PROCESSOR_URL=${PROCESSOR_URL:-}
CHAIN_SERVER_URL=${CHAIN_SERVER_URL:-}
CHAIN_ACTIVATE_URL=${CHAIN_ACTIVATE_URL:-}
ORDER_RESULT_URL=${ORDER_RESULT_URL:-}
WORKER_URL=${WORKER_URL:-}
ADAPTER_URL=${ADAPTER_URL:-}
PUBSUB_TOPIC=${PUBSUB_TOPIC}
PUBSUB_SUBSCRIPTION=${PUBSUB_SUBSCRIPTION}
PUBSUB_PUSH_SA=${PUBSUB_PUSH_SA}
SUBSCRIPTION_EXISTS=${SUBSCRIPTION_WAS_PRESENT:-not_created}
STATE
  mv "${tmp}" "${DEPLOY_STATE_FILE}"
  echo "Wrote ${DEPLOY_STATE_FILE}"
}

gcloud config set project "${PROJECT_ID}" >/dev/null
gcloud config set functions/region "${REGION}" >/dev/null

phase "A — Pub/Sub topic"
gcloud pubsub topics create "${PUBSUB_TOPIC}" --project="${PROJECT_ID}" 2>/dev/null || true

phase "B — Default runtime service account + static IAM"
PROJECT_NUMBER="$(gcloud projects describe "${PROJECT_ID}" --format='value(projectNumber)')"
RUNTIME_SA="${PROJECT_NUMBER}-compute@developer.gserviceaccount.com"
echo "RUNTIME_SA=${RUNTIME_SA}"

IAM_EXTRA=()
if [[ "${DEPLOY_USE_CONDITION_NONE:-}" == "1" ]]; then
  IAM_EXTRA=(--condition=None)
fi

echo "Project IAM: datastore.user for ${RUNTIME_SA}"
gcloud projects add-iam-policy-binding "${PROJECT_ID}" \
  --member="serviceAccount:${RUNTIME_SA}" \
  --role="roles/datastore.user" \
  "${IAM_EXTRA[@]}" 2>/dev/null || true

echo "Pub/Sub publish on topic for ${RUNTIME_SA}"
gcloud pubsub topics add-iam-policy-binding "${PUBSUB_TOPIC}" \
  --project="${PROJECT_ID}" \
  --member="serviceAccount:${RUNTIME_SA}" \
  --role="roles/pubsub.publisher" \
  "${IAM_EXTRA[@]}" 2>/dev/null || true

echo "GCS ${BUCKET_NAME}: objectAdmin for ${RUNTIME_SA}"
gcloud storage buckets add-iam-policy-binding "gs://${BUCKET_NAME}" \
  --project="${PROJECT_ID}" \
  --member="serviceAccount:${RUNTIME_SA}" \
  --role="roles/storage.objectAdmin" \
  2>/dev/null || true

echo "Secret Manager: secretAccessor on ${COORDINATES_SECRET_ID} for ${RUNTIME_SA}"
gcloud secrets add-iam-policy-binding "${COORDINATES_SECRET_ID}" \
  --project="${PROJECT_ID}" \
  --member="serviceAccount:${RUNTIME_SA}" \
  --role="roles/secretmanager.secretAccessor" \
  "${IAM_EXTRA[@]}" 2>/dev/null || true

phase "C — Processor (private) — ${FN_PROCESSOR}"
if [[ -n "${EXISTING_PROCESSOR_URL:-}" ]]; then
  PROCESSOR_URL="${EXISTING_PROCESSOR_URL%/}"
  echo "Skipping processor deploy — using EXISTING_PROCESSOR_URL"
  echo "PROCESSOR_URL=${PROCESSOR_URL}"
elif ! force_deploy && fn_exists "${FN_PROCESSOR}"; then
  PROCESSOR_URL="$(fn_uri "${FN_PROCESSOR}")"
  echo "Processor already deployed — skip (set DEPLOY_FORCE=1 to redeploy)"
  echo "PROCESSOR_URL=${PROCESSOR_URL}"
else
  pushd "${REPO_ROOT}/processor" >/dev/null
  gcloud functions deploy "${FN_PROCESSOR}" \
    --gen2 \
    --project="${PROJECT_ID}" \
    --region="${REGION}" \
    --runtime="${NODE_RUNTIME}" \
    --source=. \
    --entry-point=main \
    --trigger-http \
    --no-allow-unauthenticated \
    --set-env-vars="GOOGLE_CLOUD_PROJECT=${PROJECT_ID},PAYMENT_EVENTS_TOPIC=${PUBSUB_TOPIC},PROCESSOR_INGEST_SECRET=${PROCESSOR_INGEST_SECRET}"
  popd >/dev/null
  PROCESSOR_URL="$(fn_uri "${FN_PROCESSOR}")"
  echo "PROCESSOR_URL=${PROCESSOR_URL}"
fi

phase "D — Chain-server (private) — ${FN_CHAIN_SERVER}"
if ! force_deploy && fn_exists "${FN_CHAIN_SERVER}"; then
  CHAIN_SERVER_URL="$(fn_uri "${FN_CHAIN_SERVER}")"
  echo "Chain-server already deployed — skip (DEPLOY_FORCE=1 to redeploy)"
else
  pushd "${REPO_ROOT}/api" >/dev/null
  gcloud functions deploy "${FN_CHAIN_SERVER}" \
    --gen2 \
    --project="${PROJECT_ID}" \
    --region="${REGION}" \
    --runtime="${NODE_RUNTIME}" \
    --source=. \
    --entry-point=chainServer \
    --trigger-http \
    --no-allow-unauthenticated \
    --set-env-vars="GOOGLE_CLOUD_PROJECT=${PROJECT_ID},CHAIN_ID=137,ENS_NAME=secnum,BUCKET_NAME=${BUCKET_NAME}" \
    --set-secrets="COORDINATES=${COORDINATES_SECRET_ID}:latest"
  popd >/dev/null
  CHAIN_SERVER_URL="$(fn_uri "${FN_CHAIN_SERVER}")"
fi
echo "CHAIN_SERVER_URL=${CHAIN_SERVER_URL}"

phase "E — Chain-activate (public) — ${FN_CHAIN_ACTIVATE}"
if ! force_deploy && fn_exists "${FN_CHAIN_ACTIVATE}"; then
  CHAIN_ACTIVATE_URL="$(fn_uri "${FN_CHAIN_ACTIVATE}")"
  echo "Chain-activate already deployed — skip (DEPLOY_FORCE=1 to redeploy)"
else
  pushd "${REPO_ROOT}/api" >/dev/null
  gcloud functions deploy "${FN_CHAIN_ACTIVATE}" \
    --gen2 \
    --project="${PROJECT_ID}" \
    --region="${REGION}" \
    --runtime="${NODE_RUNTIME}" \
    --source=. \
    --entry-point=chainActivate \
    --trigger-http \
    --allow-unauthenticated \
    --set-env-vars="GOOGLE_CLOUD_PROJECT=${PROJECT_ID},CHAIN_ID=137,ENS_NAME=secnum,BUCKET_NAME=${BUCKET_NAME}" \
    --set-secrets="COORDINATES=${COORDINATES_SECRET_ID}:latest"
  popd >/dev/null
  CHAIN_ACTIVATE_URL="$(fn_uri "${FN_CHAIN_ACTIVATE}")"
fi
echo "CHAIN_ACTIVATE_URL=${CHAIN_ACTIVATE_URL}"

phase "F — Order-result (public) — ${FN_ORDER_RESULT}"
if ! force_deploy && fn_exists "${FN_ORDER_RESULT}"; then
  ORDER_RESULT_URL="$(fn_uri "${FN_ORDER_RESULT}")"
  echo "Order-result already deployed — skip (DEPLOY_FORCE=1 to redeploy)"
else
  pushd "${REPO_ROOT}/handler" >/dev/null
  gcloud functions deploy "${FN_ORDER_RESULT}" \
    --gen2 \
    --project="${PROJECT_ID}" \
    --region="${REGION}" \
    --runtime="${NODE_RUNTIME}" \
    --source=. \
    --entry-point=orderResult \
    --trigger-http \
    --allow-unauthenticated \
    --set-env-vars="GOOGLE_CLOUD_PROJECT=${PROJECT_ID},STORE_ORIGIN=${STORE_ORIGIN}"
  popd >/dev/null
  ORDER_RESULT_URL="$(fn_uri "${FN_ORDER_RESULT}")"
fi
echo "ORDER_RESULT_URL=${ORDER_RESULT_URL}"

phase "G — Payment-worker (private) — ${FN_PAYMENT_WORKER}"
if ! force_deploy && fn_exists "${FN_PAYMENT_WORKER}"; then
  WORKER_URL="$(fn_uri "${FN_PAYMENT_WORKER}")"
  echo "Payment-worker already deployed — skip (DEPLOY_FORCE=1 to redeploy)"
  echo "Note: if BLOCKCHAIN_SERVER_URL changed, redeploy worker with DEPLOY_FORCE=1"
else
  pushd "${REPO_ROOT}/handler" >/dev/null
  gcloud functions deploy "${FN_PAYMENT_WORKER}" \
    --gen2 \
    --project="${PROJECT_ID}" \
    --region="${REGION}" \
    --runtime="${NODE_RUNTIME}" \
    --source=. \
    --entry-point=worker \
    --trigger-http \
    --no-allow-unauthenticated \
    --set-env-vars="GOOGLE_CLOUD_PROJECT=${PROJECT_ID},BLOCKCHAIN_SERVER_URL=${CHAIN_SERVER_URL},STORE_ORIGIN=${STORE_ORIGIN},DEDUP_COLLECTION=payment_events_processed"
  popd >/dev/null
  WORKER_URL="$(fn_uri "${FN_PAYMENT_WORKER}")"
fi
echo "WORKER_URL=${WORKER_URL}"

phase "H — Stripe adapter (public) — ${FN_STRIPE_ADAPTER}"
# Prefer Secret Manager IDs (STRIPE_SECRET_ID / STRIPE_PROD_SECRET_ID) for production.
# Fall back to plain env vars (stripe_secret / stripe_prod_secret) for local/dev deploys.
STRIPE_ENV="PROCESSOR_URL=${PROCESSOR_URL},HANDLER_URL=${ORDER_RESULT_URL},PROCESSOR_INGEST_SECRET=${PROCESSOR_INGEST_SECRET},GOOGLE_CLOUD_PROJECT=${PROJECT_ID}"
if [[ -n "${STRIPE_SECRET_ID:-}" ]]; then
  STRIPE_ENV="${STRIPE_ENV},STRIPE_SECRET_ID=${STRIPE_SECRET_ID}"
else
  STRIPE_ENV="${STRIPE_ENV},stripe_secret=${STRIPE_SECRET}"
fi
if [[ -n "${STRIPE_PROD_SECRET_ID:-}" ]]; then
  STRIPE_ENV="${STRIPE_ENV},STRIPE_PROD_SECRET_ID=${STRIPE_PROD_SECRET_ID}"
elif [[ -n "${STRIPE_PROD_SECRET:-}" ]]; then
  STRIPE_ENV="${STRIPE_ENV},stripe_prod_secret=${STRIPE_PROD_SECRET}"
fi
if ! force_deploy && fn_exists "${FN_STRIPE_ADAPTER}"; then
  ADAPTER_URL="$(fn_uri "${FN_STRIPE_ADAPTER}")"
  echo "Stripe adapter already deployed — skip (DEPLOY_FORCE=1 to update env / code)"
else
  pushd "${REPO_ROOT}/webhook" >/dev/null
  gcloud functions deploy "${FN_STRIPE_ADAPTER}" \
    --gen2 \
    --project="${PROJECT_ID}" \
    --region="${REGION}" \
    --runtime="${PYTHON_RUNTIME}" \
    --source=. \
    --entry-point=webhook \
    --trigger-http \
    --allow-unauthenticated \
    --set-env-vars="${STRIPE_ENV}"
  popd >/dev/null
  ADAPTER_URL="$(fn_uri "${FN_STRIPE_ADAPTER}")"
fi
echo "ADAPTER_URL=${ADAPTER_URL}"

phase "I — Pub/Sub push service account + subscription"
PUBSUB_PUSH_EMAIL="${PUBSUB_PUSH_SA}@${PROJECT_ID}.iam.gserviceaccount.com"
if ! gcloud iam service-accounts describe "${PUBSUB_PUSH_EMAIL}" --project="${PROJECT_ID}" &>/dev/null; then
  gcloud iam service-accounts create "${PUBSUB_PUSH_SA}" \
    --project="${PROJECT_ID}" \
    --display-name="Pub/Sub push to payment worker"
fi

run_invoker_bind "${FN_PAYMENT_WORKER}" "serviceAccount:${PUBSUB_PUSH_EMAIL}"

# Pub/Sub must impersonate the push SA to sign OIDC tokens. Without this, subscription
# create often fails with: invalid argument PushConfig::oidc_token::service_account_email
PUBSUB_AGENT="service-${PROJECT_NUMBER}@gcp-sa-pubsub.iam.gserviceaccount.com"
echo "Allow Pub/Sub service agent to mint tokens as ${PUBSUB_PUSH_EMAIL}"
gcloud iam service-accounts add-iam-policy-binding "${PUBSUB_PUSH_EMAIL}" \
  --project="${PROJECT_ID}" \
  --member="serviceAccount:${PUBSUB_AGENT}" \
  --role="roles/iam.serviceAccountTokenCreator" \
  "${IAM_EXTRA[@]}" 2>/dev/null || true

if gcloud pubsub subscriptions describe "${PUBSUB_SUBSCRIPTION}" --project="${PROJECT_ID}" &>/dev/null; then
  SUBSCRIPTION_WAS_PRESENT=yes
  echo "Subscription ${PUBSUB_SUBSCRIPTION} already exists — delete it in console if you need to point elsewhere."
else
  gcloud pubsub subscriptions create "${PUBSUB_SUBSCRIPTION}" \
    --project="${PROJECT_ID}" \
    --topic="${PUBSUB_TOPIC}" \
    --push-endpoint="${WORKER_URL}/_pubsub" \
    --push-auth-service-account="${PUBSUB_PUSH_EMAIL}" \
    --push-auth-token-audience="${WORKER_URL}"
  SUBSCRIPTION_WAS_PRESENT=created
fi

phase "J — Cloud Run Invoker (service → service)"
# Same runtime SA by default: grant it on processor + chain-server so adapter + worker calls succeed.
run_invoker_bind "${FN_PROCESSOR}" "serviceAccount:${RUNTIME_SA}"
run_invoker_bind "${FN_CHAIN_SERVER}" "serviceAccount:${RUNTIME_SA}"

ADAPTER_SA="$(runtime_sa_email "${FN_STRIPE_ADAPTER}")"
WORKER_SA="$(runtime_sa_email "${FN_PAYMENT_WORKER}")"
echo "Deployed adapter SA: ${ADAPTER_SA}"
echo "Deployed worker SA:   ${WORKER_SA}"

if [[ "${ADAPTER_SA}" != "${RUNTIME_SA}" ]]; then
  run_invoker_bind "${FN_PROCESSOR}" "serviceAccount:${ADAPTER_SA}"
fi
if [[ "${WORKER_SA}" != "${RUNTIME_SA}" ]]; then
  run_invoker_bind "${FN_CHAIN_SERVER}" "serviceAccount:${WORKER_SA}"
fi

write_deploy_state

phase "Done — paste into Stripe / Vercel"
cat <<EOF

Stripe test webhook URL (events: checkout.session.completed, customer.subscription.deleted):
  ${ADAPTER_URL}/webhook
  (or ${ADAPTER_URL} if you route POST / only)

Vercel (production build):
  VITE_USE_PRODUCTION_URLS=true
  VITE_PROD_ORDER_RESULT_URL=${ORDER_RESULT_URL}
  VITE_PROD_CHAIN_ACTIVATE_URL=${CHAIN_ACTIVATE_URL}
  VITE_PROD_STRIPE_URL=<your Checkout session Cloud Function URL>

Optional note: order-result is public; processor + worker + chain-server are private; adapter + chain-activate are public.
EOF
